project:
  type: website
  output-dir: docs
render:
 - "*.qmd"
 - "!notebooks/"
website:
  title: "newsletter"
  site-url: https://newsletter.bradstenger.com
  description: "ADCN - Athletes Data Community Newsletter"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
  margin-header: subscribe.html
format:
  html:
    grid:
      margin-width: 410px;
    theme:
      - sandstone
      - brand
    css: styles.css



